# Theme metadata
name = "hudson"

# Is theme light or dark?
light = false

# Primary
primary = "#5498B9"
primary_light = "hsl(339, 90%, 78%)"
primary_dark = "#5498B9"

# Menu
menu_primary = "rgb(20, 22, 34)"
menu_text = "rgba(255,255,255,0.6)"
menu_text_active = "rgba(255,255,255,1)"
menu_title = "#fff"

# Home sections
home_section_odd = "hsla(231, 15%, 18%, 1)"
home_section_even = "hsla(231, 15%, 17%, 1)"
